name: Generate AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y libeccodes0 libeccodes-dev libosmgpsmap-1.0-1
        sudo apt-get install -y gdal-bin libgdal-dev
        sudo apt-get install -y libgtk-4-dev libgtk-4-1 libgirepository1.0-dev
        sudo apt-get install -y libfuse2  # Required for AppImage tools

    - name: Install Python dependencies
      run: |
        pip install git+https://github.com/vext-python/vext@32ad4d1c5f45797e244df1d2816f76b60f28e20e
        pip install pyinstaller
        pip install .

    - name: Set environment variables for X11 compatibility
      run: |
        echo "GDK_BACKEND=x11" >> $GITHUB_ENV

    - name: Generate AppImage
      run: |
        cd appimage
        bash appimagegen.sh -y

    - name: Upload AppImage as artifact
      uses: actions/upload-artifact@v3
      with:
        name: gWeatherRouting-AppImage
        path: appimage/*.AppImage

    - name: Upload AppImage to release
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: appimage/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
